### ISSUE TITLE
Crashing When Opening Zip File With Subfolder

### ISSUE THREAD

**Issue by TrademarkZe** [ahodesuka/ahoviewer#70] opened 2018-10-12 05:30 UTC
I have a bunch of ebooks that i zipped en masse which had the side effect of creating a file structure that has a subfolder like this: "Ebook.zip>>Ebook>>pg(?).png" But when i open one of these zip files the program crashes. I was wondering if it would be feasible to select the subfolder in the sidebar which would subsequently mimic the behavior of a normal folder. Or just automatically show any pictures in the zip file

**Comment by ahodesuka** [comment] 2018-10-12 08:55
I'm unable to reproduce a crash when opening a zip file that contains a directory with image files inside of it.
Something that looks like the following works as expected.
```
asdf.zip
└── asdf
    └── 105.jpg
```
Are you using the most recent version of ahoviewer?
It most likely has something to do with the zip file itself.
If possible could you upload one that causes the problem.

**Comment by TrademarkZe** [comment] 2018-10-12 16:47
I think i figured out the actual problem. When i was trying to make a file to reproduce this it wouldn't work unless i used a filename similar in length which happens to be quite long. It seems like it starts crashing somewhere around 90 char for the filenames. Sorry for the super strange issue :P

here is a link to a file that causes a crash
https://mega.nz/#!myQQHQyR!dZ3Ra0-VsERUN74DqmtfIgLeCEiWJX2TLaD_BGruv4k

**Comment by ahodesuka** [comment] 2018-10-13 08:06
I'm going to assume you are using Windows?
I'm only able to reproduce this on Windows, and I know Windows has some stupid path length restrictions.
I've pushed a fix and a new version (1.6.3).
If you are using Windows 10 you can also enable long path support as seen here:
https://www.ghacks.net/2016/05/27/microsoft-260-long-path-limit/
To avoid any problems with long filenames and/or paths.

**Closed** 2018-10-13 08:05 UTC
