### ISSUE TITLE
Bugs and improvement ideas

### ISSUE THREAD

**Issue by tayser1** [ahodesuka/ahoviewer#64] opened 2018-04-08 19:28 UTC
Bugs: 
After the app loading the new thumbnails it freeze and if i try to scroll it crashes.
tag-suggestion doesn´t work on windows 

Options:
Save session and restore previous session option.
Smoother Zoom with mouse wheel.
Add only searched tags to the saved filename.
Add tag-suggestion while searching as option

**Comment by As4shi** [comment] 2018-05-12 01:34
About the crash bug, if you click and hold on the bottom of the scroll bar, it will indeed crash/freeze, i believe that if you keep scrolling with the mouse wheel it will also crash.

To "fix" this, just don't hold it, drag the scroll or just croll with your mouse until the very bottom and wait for it to finish loading the new thumbnails, this way it will not freeze, i believe it tries to constantly search and load new thumbnails until it can't handle it anymore and just freeze.

Not sure what the tag-suggestion is all about.

The save session, would be really useful if it saves the "scroll bar location".

**Comment by ahodesuka** [comment] 2018-05-12 01:49
Okay, I'm able to reproduce the crash and I'll work on a fix for it soon.

The tag auto-complete works fine for me on Windows.

``` Save session and restore previous session option.```
This is something I'll think about implementing, but if it's not something that I'd personally use I probably won't do it myself.  A pull request is always welcome though.

**Comment by ahodesuka** [comment] 2018-05-12 06:58
The crash while using the booru browser should be fixed as of 7bb1f32 .

**Comment by ahodesuka** [comment] 2018-09-13 12:58
After some thought I don't think it will be worth creating a session save/restore function because of some fundamental problems.  ahoviewer's booru browser is meant to be a much more temporary viewing utility.
It's better to just save the images locally yourself, and view them again later.

**Closed by ahodesuka** 2018-09-13 12:58 UTC
